In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day  Transportation Expense  \
0         0         0         0         1      7    1                     289   
1         0         0         0         0      7    1                     118   
2         0         0         0         1      7    2                     179   
3         1         0         0         0      7    3                     279   
4         0         0         0         1      7    3                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [4]:
#Making targests
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>
                           data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [8]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [9]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day  \
0           0         0         0         1      7    1   
1           0         0         0         0      7    1   
2           0         0         0         1      7    2   
3           1         0         0         0      7    3   
4           0         0         0         1      7    3   
..        ...       ...       ...       ...    ...  ...   
695         1         0         0         0      5    2   
696         1         0         0         0      5    2   
697         1         0         0         0      5    3   
698         0         0         0         1      5    3   
699         0         0         0         1      5    3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [10]:
data_with_targets['Excessive abseteesim']=targets

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
#Inputs values
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day  \
0           0         0         0         1      7    1   
1           0         0         0         0      7    1   
2           0         0         0         1      7    2   
3           1         0         0         0      7    3   
4           0         0         0         1      7    3   
..        ...       ...       ...       ...    ...  ...   
695         1         0         0         0      5    2   
696         1         0         0         0      5    2   
697         1         0         0         0      5    3   
698         0         0         0         1      5    3   
699         0         0         0         1      5    3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [13]:
unscaled_inputs=data_with_targets.iloc[:,:14]

In [14]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day  \
0           0         0         0         1      7    1   
1           0         0         0         0      7    1   
2           0         0         0         1      7    2   
3           1         0         0         0      7    3   
4           0         0         0         1      7    3   
..        ...       ...       ...       ...    ...  ...   
695         1         0         0         0      5    2   
696         1         0         0         0      5    2   
697         1         0         0         0      5    3   
698         0         0         0         1      5    3   
699         0         0         0         1      5    3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
absetism_scaler=StandardScaler()
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month', 'Day',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
absetism_scaler = CustomScaler(columns_to_scale)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [20]:
absetism_scaler.fit(unscaled_inputs)

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [46]:
scaler_data=absetism_scaler.transform(unscaled_inputs)

In [47]:
scaler_data

Reason_1  Reason_2  Reason_3  Reason_4     Month       Day  \
0           0         0         0         1  0.030796 -0.800950   
1           0         0         0         0  0.030796 -0.800950   
2           0         0         0         1  0.030796 -0.232900   
3           1         0         0         0  0.030796  0.335149   
4           0         0         0         1  0.030796  0.335149   
..        ...       ...       ...       ...       ...       ...   
695         1         0         0         0 -0.568019 -0.232900   
696         1         0         0         0 -0.568019 -0.232900   
697         1         0         0         0 -0.568019  0.335149   
698         0         0         0         1 -0.568019  0.335149   
699         0         0         0         1 -0.568019  0.335149   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [23]:
scaler_data.shape

(700, 14)

In [24]:
#Spleting the data into train and test

from sklearn.model_selection import train_test_split

In [25]:
train_test_split(scaler_data,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4     Month       Day  \
 125         0         0         0         1 -1.765648  0.335149   
 582         1         0         0         0 -1.765648 -0.232900   
 507         1         0         0         0 -0.568019 -0.232900   
 572         0         0         0         1 -0.867426  2.039298   
 636         0         0         0         1 -1.166834 -1.368999   
 ..        ...       ...       ...       ...       ...       ...   
 37          1         0         0         0  0.330204  0.335149   
 668         0         1         0         0 -0.867426 -0.800950   
 195         0         0         0         1 -0.867426  0.903199   
 312         0         0         0         0  0.929019  0.335149   
 278         1         0         0         0  0.629611 -0.232900   
 
      Transportation Expense  Distance to Work       Age  \
 125               -1.574681         -1.344669  0.091435   
 582                1.005844          0.412816 -0.536062   
 5

In [26]:
x_train,x_test,y_train,y_test=train_test_split(scaler_data,targets,train_size=0.8,random_state=20)

In [27]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [28]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


In [29]:
#Training the data and apply machine learning
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [30]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [31]:
reg.score(x_train,y_train)

0.7660714285714286

In [32]:
#Checking accuracy manually

model_output=reg.predict(x_train)
model_output

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [34]:
model_output==y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum(model_output==y_train)

429

In [36]:
model_output.shape[0]

560

In [37]:
np.sum(model_output==y_train)/model_output.shape[0]

0.7660714285714286

In [38]:
#Finding coeffecient and intercept
reg.intercept_

array([-1.60991897])

In [39]:
reg.coef_

array([[ 2.78809595,  0.92273475,  3.10358519,  0.81724476,  0.01379249,
        -0.07594179,  0.62737945, -0.02990801, -0.17344994, -0.02273184,
         0.2816181 , -0.27058935,  0.36063506, -0.27446609]])

In [40]:
feature_name=unscaled_inputs.columns.values

In [41]:
#Creating summary table
summary_table=pd.DataFrame(columns=['Features name'],data=feature_name)
summary_table['Coefficients']=np.transpose(reg.coef_)
summary_table

Features name  Coefficients
0                  Reason_1      2.788096
1                  Reason_2      0.922735
2                  Reason_3      3.103585
3                  Reason_4      0.817245
4                     Month      0.013792
5                       Day     -0.075942
6    Transportation Expense      0.627379
7          Distance to Work     -0.029908
8                       Age     -0.173450
9   Daily Work Load Average     -0.022732
10          Body Mass Index      0.281618
11                Education     -0.270589
12                 Children      0.360635
13                     Pets     -0.274466

In [42]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()

In [43]:
summary_table

Features name  Coefficients
0                 intercept     -1.609919
1                  Reason_1      2.788096
2                  Reason_2      0.922735
3                  Reason_3      3.103585
4                  Reason_4      0.817245
5                     Month      0.013792
6                       Day     -0.075942
7    Transportation Expense      0.627379
8          Distance to Work     -0.029908
9                       Age     -0.173450
10  Daily Work Load Average     -0.022732
11          Body Mass Index      0.281618
12                Education     -0.270589
13                 Children      0.360635
14                     Pets     -0.274466

In [44]:
#interpreting the coeffiecients
summary_table['Odds ratio']=np.exp(summary_table.Coefficients)
summary_table

Features name  Coefficients  Odds ratio
0                 intercept     -1.609919    0.199904
1                  Reason_1      2.788096   16.250049
2                  Reason_2      0.922735    2.516162
3                  Reason_3      3.103585   22.277678
4                  Reason_4      0.817245    2.264253
5                     Month      0.013792    1.013888
6                       Day     -0.075942    0.926870
7    Transportation Expense      0.627379    1.872697
8          Distance to Work     -0.029908    0.970535
9                       Age     -0.173450    0.840759
10  Daily Work Load Average     -0.022732    0.977525
11          Body Mass Index      0.281618    1.325273
12                Education     -0.270589    0.762930
13                 Children      0.360635    1.434240
14                     Pets     -0.274466    0.759978

In [45]:
summary_table.sort_values('Odds ratio',ascending=False)

Features name  Coefficients  Odds ratio
3                  Reason_3      3.103585   22.277678
1                  Reason_1      2.788096   16.250049
2                  Reason_2      0.922735    2.516162
4                  Reason_4      0.817245    2.264253
7    Transportation Expense      0.627379    1.872697
13                 Children      0.360635    1.434240
11          Body Mass Index      0.281618    1.325273
5                     Month      0.013792    1.013888
10  Daily Work Load Average     -0.022732    0.977525
8          Distance to Work     -0.029908    0.970535
6                       Day     -0.075942    0.926870
9                       Age     -0.173450    0.840759
12                Education     -0.270589    0.762930
14                     Pets     -0.274466    0.759978
0                 intercept     -1.609919    0.199904